/**
 * Seed file — Eredivisie 2026/27, echte selecties per club.
 * Run with: npm run db:seed
 */
import "dotenv/config";
import { players } from "../../../shared/schema.js";
import { db } from "./index.js";

const PLAYERS: Array<Omit<typeof players.$inferInsert, "id">> = [
  // ===================== ADO DEN HAAG =====================
  { name: "S. Eekhout", club: "ADO Den Haag", position: "GK", price: 3.0 },
  { name: "K. Nikièma", club: "ADO Den Haag", position: "GK", price: 2.5 },
  { name: "C. Kramer", club: "ADO Den Haag", position: "GK", price: 2.5 },
  { name: "C. Ratford", club: "ADO Den Haag", position: "GK", price: 2.0 },
  { name: "M. Waem", club: "ADO Den Haag", position: "DEF", price: 3.5 },
  { name: "M. Hokke", club: "ADO Den Haag", position: "DEF", price: 3.5 },
  { name: "P. Mulder", club: "ADO Den Haag", position: "DEF", price: 3.0 },
  { name: "S. Bergtop", club: "ADO Den Haag", position: "DEF", price: 3.0 },
  { name: "S. Oumar Sylla", club: "ADO Den Haag", position: "DEF", price: 3.0 },
  { name: "I. de Ruijter", club: "ADO Den Haag", position: "DEF", price: 3.0 },
  { name: "F. de Bruin", club: "ADO Den Haag", position: "MID", price: 4.0 },
  { name: "J. Kilo", club: "ADO Den Haag", position: "MID", price: 3.5 },
  { name: "J. Hawkins", club: "ADO Den Haag", position: "MID", price: 3.5 },
  { name: "D. van Loenen", club: "ADO Den Haag", position: "MID", price: 3.5 },
  { name: "M. Jiménez", club: "ADO Den Haag", position: "MID", price: 4.0 },
  { name: "J. Vlak", club: "ADO Den Haag", position: "MID", price: 3.0 },
  { name: "C. Peupion", club: "ADO Den Haag", position: "FWD", price: 5.5 },
  { name: "L. Reischl", club: "ADO Den Haag", position: "FWD", price: 4.5 },
  { name: "E. Rottier", club: "ADO Den Haag", position: "FWD", price: 4.0 },
  { name: "J. Bal", club: "ADO Den Haag", position: "FWD", price: 4.0 },
  { name: "D. van Mieghem", club: "ADO Den Haag", position: "FWD", price: 4.5 },
  { name: "N. Thomas", club: "ADO Den Haag", position: "FWD", price: 3.5 },

  // ===================== AJAX =====================
  { name: "A. El Hani", club: "Ajax", position: "GK", price: 5.0 },
  { name: "J. Heerkens", club: "Ajax", position: "GK", price: 4.0 },
  { name: "M. Paes", club: "Ajax", position: "GK", price: 6.0 },
  { name: "V. van der Velde", club: "Ajax", position: "GK", price: 3.0 },
  { name: "P. Reverson", club: "Ajax", position: "GK", price: 3.0 },
  { name: "A. Gaaei", club: "Ajax", position: "DEF", price: 10.0 },
  { name: "J. Šutalo", club: "Ajax", position: "DEF", price: 11.0 },
  { name: "A. Appiah", club: "Ajax", position: "DEF", price: 7.0 },
  { name: "M. van der Lans", club: "Ajax", position: "DEF", price: 6.0 },
  { name: "A. Bouwman", club: "Ajax", position: "DEF", price: 5.0 },
  { name: "Y. Baas", club: "Ajax", position: "DEF", price: 5.0 },
  { name: "M. Muzungu", club: "Ajax", position: "DEF", price: 4.5 },
  { name: "K. Kasanwirjo", club: "Ajax", position: "DEF", price: 5.5 },
  { name: "O. Wijndal", club: "Ajax", position: "DEF", price: 7.0 },
  { name: "Caio Henrique", club: "Ajax", position: "DEF", price: 9.0 },
  { name: "K. Itakura", club: "Ajax", position: "DEF", price: 8.0 },
  { name: "S. Tilborg", club: "Ajax", position: "DEF", price: 4.0 },
  { name: "J. Johnson", club: "Ajax", position: "DEF", price: 5.0 },
  { name: "Lucas Rosa", club: "Ajax", position: "DEF", price: 4.5 },
  { name: "D. van der Vaart", club: "Ajax", position: "MID", price: 7.0 },
  { name: "A. Ouazane", club: "Ajax", position: "MID", price: 6.0 },
  { name: "O. Gloukh", club: "Ajax", position: "MID", price: 14.0 },
  { name: "J. Mokio", club: "Ajax", position: "MID", price: 5.0 },
  { name: "M. Abdalla", club: "Ajax", position: "MID", price: 5.0 },
  { name: "D. O'Niel", club: "Ajax", position: "MID", price: 5.5 },
  { name: "S. Steur", club: "Ajax", position: "MID", price: 4.5 },
  { name: "Y. Regeer", club: "Ajax", position: "MID", price: 9.0 },
  { name: "K. Fitz-Jim", club: "Ajax", position: "MID", price: 8.0 },
  { name: "D. Klaassen", club: "Ajax", position: "MID", price: 7.0 },
  { name: "M. Verkuijl", club: "Ajax", position: "MID", price: 4.0 },
  { name: "T. Peters", club: "Ajax", position: "MID", price: 4.0 },
  { name: "D. Konadu", club: "Ajax", position: "FWD", price: 8.0 },
  { name: "E. Ünüvar", club: "Ajax", position: "FWD", price: 9.0 },
  { name: "K. Dolberg", club: "Ajax", position: "FWD", price: 13.0 },
  { name: "S. Berghuis", club: "Ajax", position: "FWD", price: 12.0 },
  { name: "P. Nash", club: "Ajax", position: "FWD", price: 6.0 },
  { name: "M. Carrizo", club: "Ajax", position: "FWD", price: 5.5 },
  { name: "R. Bounida", club: "Ajax", position: "FWD", price: 7.0 },
  { name: "O. Edvardsen", club: "Ajax", position: "FWD", price: 7.5 },
  { name: "M. Godts", club: "Ajax", position: "FWD", price: 10.0 },

  // ===================== AZ =====================
  { name: "H. Verhulst", club: "AZ", position: "GK", price: 5.5 },
  { name: "J. De Busser", club: "AZ", position: "GK", price: 3.5 },
  { name: "R. Owusu-Oduro", club: "AZ", position: "GK", price: 3.5 },
  { name: "J. Schipper", club: "AZ", position: "GK", price: 3.0 },
  { name: "J. Zoet", club: "AZ", position: "GK", price: 3.0 },
  { name: "W. Goes", club: "AZ", position: "DEF", price: 8.0 },
  { name: "D. Kasius", club: "AZ", position: "DEF", price: 7.0 },
  { name: "Alexandre Penetra", club: "AZ", position: "DEF", price: 6.0 },
  { name: "S. Maikuma", club: "AZ", position: "DEF", price: 6.5 },
  { name: "J. Zwart", club: "AZ", position: "DEF", price: 5.5 },
  { name: "B. van Duijl", club: "AZ", position: "DEF", price: 5.0 },
  { name: "M. Menu", club: "AZ", position: "DEF", price: 5.0 },
  { name: "M. Dekker", club: "AZ", position: "DEF", price: 4.5 },
  { name: "R. Ichihara", club: "AZ", position: "DEF", price: 5.0 },
  { name: "M. de Wit", club: "AZ", position: "DEF", price: 5.0 },
  { name: "M. Chávez", club: "AZ", position: "DEF", price: 5.5 },
  { name: "E. Dijkstra", club: "AZ", position: "DEF", price: 4.0 },
  { name: "M. Šín", club: "AZ", position: "MID", price: 7.0 },
  { name: "K. Boogaard", club: "AZ", position: "MID", price: 6.0 },
  { name: "J. Clasie", club: "AZ", position: "MID", price: 7.0 },
  { name: "K. Smit", club: "AZ", position: "MID", price: 5.5 },
  { name: "P. Koopmeiners", club: "AZ", position: "MID", price: 8.0 },
  { name: "R. Robbemond", club: "AZ", position: "MID", price: 4.5 },
  { name: "S. Mijnans", club: "AZ", position: "MID", price: 9.0 },
  { name: "A. Oufkir", club: "AZ", position: "FWD", price: 7.0 },
  { name: "T. Parrott", club: "AZ", position: "FWD", price: 9.0 },
  { name: "I. Sadiq", club: "AZ", position: "FWD", price: 9.0 },
  { name: "R. Daal", club: "AZ", position: "FWD", price: 6.0 },
  { name: "W. Bouziane", club: "AZ", position: "FWD", price: 5.5 },
  { name: "J. Hartog", club: "AZ", position: "FWD", price: 5.0 },
  { name: "Weslley Patati", club: "AZ", position: "FWD", price: 6.5 },
  { name: "M. Meerdink", club: "AZ", position: "FWD", price: 5.5 },
  { name: "B. Kovács", club: "AZ", position: "FWD", price: 5.0 },
  { name: "J. Hornkamp", club: "AZ", position: "FWD", price: 7.0 },
  { name: "I. Jensen", club: "AZ", position: "FWD", price: 5.5 },

  // ===================== EXCELSIOR ROTTERDAM =====================
  { name: "T. Holla", club: "Excelsior", position: "GK", price: 3.5 },
  { name: "S. van Gassel", club: "Excelsior", position: "GK", price: 3.0 },
  { name: "C. Raatsie", club: "Excelsior", position: "GK", price: 2.5 },
  { name: "H. Akujobi", club: "Excelsior", position: "DEF", price: 4.0 },
  { name: "S. Janssen", club: "Excelsior", position: "DEF", price: 4.0 },
  { name: "S. Henderikx", club: "Excelsior", position: "DEF", price: 3.5 },
  { name: "R. Meissen", club: "Excelsior", position: "DEF", price: 3.5 },
  { name: "M. van de Wetering", club: "Excelsior", position: "DEF", price: 4.0 },
  { name: "C. Widell", club: "Excelsior", position: "DEF", price: 3.5 },
  { name: "M. Tielemans", club: "Excelsior", position: "MID", price: 5.5 },
  { name: "I. Yegoian", club: "Excelsior", position: "MID", price: 4.0 },
  { name: "G. Cairo", club: "Excelsior", position: "MID", price: 4.5 },
  { name: "G. van den Berg", club: "Excelsior", position: "MID", price: 5.0 },
  { name: "A. Carlén", club: "Excelsior", position: "MID", price: 4.5 },
  { name: "D. van Vianen", club: "Excelsior", position: "MID", price: 4.0 },
  { name: "N. El Hamdaoui", club: "Excelsior", position: "MID", price: 4.5 },
  { name: "L. Hartjes", club: "Excelsior", position: "MID", price: 3.5 },
  { name: "N. Naujoks", club: "Excelsior", position: "MID", price: 3.5 },
  { name: "D. Sanches Fernandes", club: "Excelsior", position: "FWD", price: 5.0 },
  { name: "N. Groen", club: "Excelsior", position: "FWD", price: 5.0 },
  { name: "E. Hansson", club: "Excelsior", position: "FWD", price: 5.5 },
  { name: "G. de Regt", club: "Excelsior", position: "FWD", price: 4.5 },
  { name: "K. Bos", club: "Excelsior", position: "FWD", price: 4.0 },
  { name: "J. Bergraaf", club: "Excelsior", position: "FWD", price: 4.0 },

  // ===================== FC GRONINGEN =====================
  { name: "S. Petiet", club: "FC Groningen", position: "GK", price: 4.0 },
  { name: "L. Štubljar", club: "FC Groningen", position: "GK", price: 3.5 },
  { name: "E. Vaessen", club: "FC Groningen", position: "GK", price: 4.0 },
  { name: "M. Rente", club: "FC Groningen", position: "DEF", price: 5.0 },
  { name: "E. van der Laan", club: "FC Groningen", position: "DEF", price: 4.5 },
  { name: "S. Bouland", club: "FC Groningen", position: "DEF", price: 4.5 },
  { name: "W. Prins", club: "FC Groningen", position: "DEF", price: 4.0 },
  { name: "T. Mercera", club: "FC Groningen", position: "DEF", price: 4.0 },
  { name: "R. Kelder", club: "FC Groningen", position: "DEF", price: 3.5 },
  { name: "T. Blokzijl", club: "FC Groningen", position: "DEF", price: 3.5 },
  { name: "J. Dillema", club: "FC Groningen", position: "MID", price: 5.0 },
  { name: "T. Land", club: "FC Groningen", position: "MID", price: 5.5 },
  { name: "J. Schreuders", club: "FC Groningen", position: "MID", price: 5.0 },
  { name: "D. van der Werff", club: "FC Groningen", position: "MID", price: 4.5 },
  { name: "T. de Jonge", club: "FC Groningen", position: "MID", price: 4.0 },
  { name: "S. Resink", club: "FC Groningen", position: "MID", price: 4.0 },
  { name: "Y. Holder", club: "FC Groningen", position: "MID", price: 5.0 },
  { name: "R. Metu", club: "FC Groningen", position: "FWD", price: 6.0 },
  { name: "M. Hoekstra", club: "FC Groningen", position: "FWD", price: 5.5 },
  { name: "B. Willumsson", club: "FC Groningen", position: "FWD", price: 6.0 },
  { name: "T. van Bergen", club: "FC Groningen", position: "FWD", price: 7.0 },
  { name: "O. Zawada", club: "FC Groningen", position: "FWD", price: 6.5 },

  // ===================== FC TWENTE =====================
  { name: "I. El Maach", club: "FC Twente", position: "GK", price: 4.5 },
  { name: "L. Unnerstall", club: "FC Twente", position: "GK", price: 5.5 },
  { name: "P. Tytoń", club: "FC Twente", position: "GK", price: 3.0 },
  { name: "Y. Gerritsen", club: "FC Twente", position: "GK", price: 2.5 },
  { name: "Guilherme Peixoto", club: "FC Twente", position: "DEF", price: 5.5 },
  { name: "R. Pröpper", club: "FC Twente", position: "DEF", price: 6.0 },
  { name: "A. Adelgaard", club: "FC Twente", position: "DEF", price: 5.5 },
  { name: "S. Lemkin", club: "FC Twente", position: "DEF", price: 5.0 },
  { name: "R. Nijstad", club: "FC Twente", position: "DEF", price: 4.5 },
  { name: "M. Bruns", club: "FC Twente", position: "DEF", price: 4.5 },
  { name: "M. Hilgers", club: "FC Twente", position: "DEF", price: 11.0 },
  { name: "B. Titulaer", club: "FC Twente", position: "DEF", price: 4.0 },
  { name: "B. van Rooij", club: "FC Twente", position: "DEF", price: 5.0 },
  { name: "B. Nagel", club: "FC Twente", position: "MID", price: 6.0 },
  { name: "M. Kjølø", club: "FC Twente", position: "MID", price: 7.0 },
  { name: "K. Hlynsson", club: "FC Twente", position: "MID", price: 8.0 },
  { name: "S. Ørjasæter", club: "FC Twente", position: "MID", price: 7.0 },
  { name: "D. Weidmann", club: "FC Twente", position: "MID", price: 6.5 },
  { name: "N. Groenewald", club: "FC Twente", position: "MID", price: 5.0 },
  { name: "T. van den Belt", club: "FC Twente", position: "MID", price: 7.5 },
  { name: "A. Verschueren", club: "FC Twente", position: "MID", price: 6.0 },
  { name: "S. Lammers", club: "FC Twente", position: "FWD", price: 11.0 },
  { name: "L. Vennegoor of Hesselink", club: "FC Twente", position: "FWD", price: 6.0 },
  { name: "M. Pjaca", club: "FC Twente", position: "FWD", price: 7.0 },
  { name: "T. Booth", club: "FC Twente", position: "FWD", price: 6.5 },
  { name: "D. Rots", club: "FC Twente", position: "FWD", price: 8.0 },
  { name: "O. Panneflek", club: "FC Twente", position: "FWD", price: 7.0 },

  // ===================== FC UTRECHT =====================
  { name: "K. Gadellaa", club: "FC Utrecht", position: "GK", price: 5.0 },
  { name: "M. Brouwer", club: "FC Utrecht", position: "GK", price: 4.0 },
  { name: "J. Eversen", club: "FC Utrecht", position: "GK", price: 3.5 },
  { name: "M. Eppink", club: "FC Utrecht", position: "GK", price: 3.0 },
  { name: "V. Barkas", club: "FC Utrecht", position: "GK", price: 4.5 },
  { name: "S. Horemans", club: "FC Utrecht", position: "DEF", price: 5.0 },
  { name: "N. Viereck", club: "FC Utrecht", position: "DEF", price: 5.5 },
  { name: "N. Vesterlund", club: "FC Utrecht", position: "DEF", price: 5.5 },
  { name: "V. Plantinga", club: "FC Utrecht", position: "DEF", price: 5.0 },
  { name: "M. Didden", club: "FC Utrecht", position: "DEF", price: 4.5 },
  { name: "P. Kloosterboer", club: "FC Utrecht", position: "DEF", price: 4.0 },
  { name: "E. Adiele", club: "FC Utrecht", position: "DEF", price: 4.5 },
  { name: "M. Eerdhuijzen", club: "FC Utrecht", position: "DEF", price: 5.0 },
  { name: "C. Bozdoğan", club: "FC Utrecht", position: "MID", price: 6.5 },
  { name: "R. El Arguioui", club: "FC Utrecht", position: "MID", price: 5.5 },
  { name: "D. de Wit", club: "FC Utrecht", position: "MID", price: 7.0 },
  { name: "V. Jensen", club: "FC Utrecht", position: "MID", price: 6.0 },
  { name: "A. Engwanda", club: "FC Utrecht", position: "MID", price: 5.0 },
  { name: "J. van Ommeren", club: "FC Utrecht", position: "MID", price: 5.0 },
  { name: "O. Agougil", club: "FC Utrecht", position: "MID", price: 5.0 },
  { name: "Zidane Iqbal", club: "FC Utrecht", position: "MID", price: 8.0 },
  { name: "S. Haller", club: "FC Utrecht", position: "FWD", price: 14.0 },
  { name: "Miguel Rodríguez", club: "FC Utrecht", position: "FWD", price: 7.0 },
  { name: "A. Stepanov", club: "FC Utrecht", position: "FWD", price: 5.5 },
  { name: "E. Demircan", club: "FC Utrecht", position: "FWD", price: 5.5 },
  { name: "B. Menzo", club: "FC Utrecht", position: "FWD", price: 6.0 },
  { name: "Y. Cathline", club: "FC Utrecht", position: "FWD", price: 6.5 },
  { name: "A. Blake", club: "FC Utrecht", position: "FWD", price: 5.0 },
  { name: "D. Min", club: "FC Utrecht", position: "FWD", price: 5.0 },
  { name: "E. Owen", club: "FC Utrecht", position: "FWD", price: 5.5 },
  { name: "D. Bouchta", club: "FC Utrecht", position: "FWD", price: 4.5 },

  // ===================== FEYENOORD =====================
  { name: "T. Wellenreuther", club: "Feyenoord", position: "GK", price: 8.0 },
  { name: "M. Berger", club: "Feyenoord", position: "GK", price: 4.0 },
  { name: "I. Ka", club: "Feyenoord", position: "GK", price: 3.5 },
  { name: "L. Bossin", club: "Feyenoord", position: "GK", price: 3.0 },
  { name: "J. St. Juste", club: "Feyenoord", position: "DEF", price: 9.0 },
  { name: "J. Bos", club: "Feyenoord", position: "DEF", price: 5.5 },
  { name: "G. Smal", club: "Feyenoord", position: "DEF", price: 7.0 },
  { name: "B. Nieuwkoop", club: "Feyenoord", position: "DEF", price: 6.0 },
  { name: "T. Watanabe", club: "Feyenoord", position: "DEF", price: 8.0 },
  { name: "J. Lotomba", club: "Feyenoord", position: "DEF", price: 6.5 },
  { name: "T. Beelen", club: "Feyenoord", position: "DEF", price: 6.0 },
  { name: "A. Ahmedhodžić", club: "Feyenoord", position: "DEF", price: 8.5 },
  { name: "G. Read", club: "Feyenoord", position: "DEF", price: 5.0 },
  { name: "M. Deijl", club: "Feyenoord", position: "DEF", price: 5.0 },
  { name: "T. Kraaijeveld", club: "Feyenoord", position: "MID", price: 5.5 },
  { name: "L. Valente", club: "Feyenoord", position: "MID", price: 6.0 },
  { name: "C. Vanhoutte", club: "Feyenoord", position: "MID", price: 6.5 },
  { name: "A. Nahany", club: "Feyenoord", position: "MID", price: 5.0 },
  { name: "J. Schaken", club: "Feyenoord", position: "MID", price: 5.0 },
  { name: "I. Grootfaam", club: "Feyenoord", position: "MID", price: 5.0 },
  { name: "J. Moder", club: "Feyenoord", position: "MID", price: 7.0 },
  { name: "S. 't Zand", club: "Feyenoord", position: "MID", price: 6.0 },
  { name: "S. Steijn", club: "Feyenoord", position: "MID", price: 11.0 },
  { name: "O. Targhalline", club: "Feyenoord", position: "MID", price: 6.5 },
  { name: "H. Agboluaje", club: "Feyenoord", position: "MID", price: 5.5 },
  { name: "T. van den Elshout", club: "Feyenoord", position: "MID", price: 5.0 },
  { name: "Hwang In-Beom", club: "Feyenoord", position: "MID", price: 8.0 },
  { name: "L. Sauer", club: "Feyenoord", position: "FWD", price: 8.0 },
  { name: "G. Diarra", club: "Feyenoord", position: "FWD", price: 7.0 },
  { name: "S. van Persie", club: "Feyenoord", position: "FWD", price: 13.0 },
  { name: "J. Zinhagel", club: "Feyenoord", position: "FWD", price: 8.0 },
  { name: "C. Tengstedt", club: "Feyenoord", position: "FWD", price: 12.0 },
  { name: "A. Ueda", club: "Feyenoord", position: "FWD", price: 14.0 },
  { name: "R. Sterling", club: "Feyenoord", position: "FWD", price: 16.0 },
  { name: "Gonçalo Borges", club: "Feyenoord", position: "FWD", price: 10.0 },
  { name: "A. Sliti", club: "Feyenoord", position: "FWD", price: 7.0 },
  { name: "A. Hadj Moussa", club: "Feyenoord", position: "FWD", price: 9.0 },
  { name: "Nacho Ferri", club: "Feyenoord", position: "FWD", price: 6.0 },

  // ===================== FORTUNA SITTARD =====================
  { name: "L. Van Parys", club: "Fortuna Sittard", position: "GK", price: 3.5 },
  { name: "L. Koopmans", club: "Fortuna Sittard", position: "GK", price: 4.0 },
  { name: "R. Bayram", club: "Fortuna Sittard", position: "GK", price: 3.0 },
  { name: "M. Branderhorst", club: "Fortuna Sittard", position: "GK", price: 4.5 },
  { name: "J. Hubner", club: "Fortuna Sittard", position: "DEF", price: 4.5 },
  { name: "Ivo Pinto", club: "Fortuna Sittard", position: "DEF", price: 4.5 },
  { name: "D. Sinkgraven", club: "Fortuna Sittard", position: "DEF", price: 5.0 },
  { name: "J. Dahlhaus", club: "Fortuna Sittard", position: "DEF", price: 4.0 },
  { name: "S. van Ottele", club: "Fortuna Sittard", position: "DEF", price: 4.0 },
  { name: "A. Bah", club: "Fortuna Sittard", position: "DEF", price: 4.5 },
  { name: "S. Adewoye", club: "Fortuna Sittard", position: "DEF", price: 4.0 },
  { name: "Iván Márquez", club: "Fortuna Sittard", position: "DEF", price: 5.0 },
  { name: "G. Büyükhan", club: "Fortuna Sittard", position: "MID", price: 5.5 },
  { name: "L. Tunjić", club: "Fortuna Sittard", position: "MID", price: 5.0 },
  { name: "S. Bastien", club: "Fortuna Sittard", position: "MID", price: 6.0 },
  { name: "É. Michut", club: "Fortuna Sittard", position: "MID", price: 6.5 },
  { name: "P. Brittijn", club: "Fortuna Sittard", position: "MID", price: 4.5 },
  { name: "A. Halilović", club: "Fortuna Sittard", position: "MID", price: 6.0 },
  { name: "A. Laoukili", club: "Fortuna Sittard", position: "MID", price: 5.0 },
  { name: "M. Gbemou", club: "Fortuna Sittard", position: "MID", price: 5.0 },
  { name: "W. Elasri", club: "Fortuna Sittard", position: "MID", price: 5.5 },
  { name: "M. Ihattaren", club: "Fortuna Sittard", position: "MID", price: 6.5 },
  { name: "Y. Oukili", club: "Fortuna Sittard", position: "MID", price: 5.0 },
  { name: "H. Korkmazyürek", club: "Fortuna Sittard", position: "MID", price: 4.5 },
  { name: "L. Zeefuik", club: "Fortuna Sittard", position: "FWD", price: 6.5 },
  { name: "K. Peterson", club: "Fortuna Sittard", position: "FWD", price: 6.0 },
  { name: "O. Johnson", club: "Fortuna Sittard", position: "FWD", price: 6.0 },

  // ===================== GO AHEAD EAGLES =====================
  { name: "N. Verdoni", club: "Go Ahead Eagles", position: "GK", price: 4.5 },
  { name: "G. Nauber", club: "Go Ahead Eagles", position: "DEF", price: 5.5 },
  { name: "A. Sampsted", club: "Go Ahead Eagles", position: "DEF", price: 5.5 },
  { name: "P. Saathof", club: "Go Ahead Eagles", position: "DEF", price: 4.5 },
  { name: "G. van Zwam", club: "Go Ahead Eagles", position: "DEF", price: 4.0 },
  { name: "E. Waayers", club: "Go Ahead Eagles", position: "DEF", price: 4.0 },
  { name: "J. Dirksen", club: "Go Ahead Eagles", position: "DEF", price: 4.0 },
  { name: "J. Kramer", club: "Go Ahead Eagles", position: "DEF", price: 5.0 },
  { name: "D. James", club: "Go Ahead Eagles", position: "DEF", price: 5.0 },
  { name: "S. Tengstedt", club: "Go Ahead Eagles", position: "MID", price: 6.5 },
  { name: "Y. Salah Rahmouni", club: "Go Ahead Eagles", position: "MID", price: 5.5 },
  { name: "R. Weijenberg", club: "Go Ahead Eagles", position: "MID", price: 5.0 },
  { name: "J. Breum", club: "Go Ahead Eagles", position: "MID", price: 6.0 },
  { name: "E. Linthorst", club: "Go Ahead Eagles", position: "MID", price: 4.5 },
  { name: "M. Suray", club: "Go Ahead Eagles", position: "MID", price: 5.5 },
  { name: "M. Meulensteen", club: "Go Ahead Eagles", position: "MID", price: 5.0 },
  { name: "O. Sivertsen", club: "Go Ahead Eagles", position: "FWD", price: 7.5 },
  { name: "S. Sigurðarson", club: "Go Ahead Eagles", position: "FWD", price: 6.5 },
  { name: "O. Boakye", club: "Go Ahead Eagles", position: "FWD", price: 6.0 },
  { name: "D. Tijman", club: "Go Ahead Eagles", position: "FWD", price: 5.5 },
  { name: "V. Edvardsen", club: "Go Ahead Eagles", position: "FWD", price: 6.0 },
  { name: "T. Baeten", club: "Go Ahead Eagles", position: "FWD", price: 6.5 },
  { name: "R. Margaret", club: "Go Ahead Eagles", position: "FWD", price: 5.5 },

  // ===================== N.E.C. NIJMEGEN =====================
  { name: "G. Crettaz", club: "NEC Nijmegen", position: "GK", price: 4.5 },
  { name: "M. Overmars", club: "NEC Nijmegen", position: "GK", price: 3.5 },
  { name: "F. Entius", club: "NEC Nijmegen", position: "GK", price: 3.0 },
  { name: "M. Renssen", club: "NEC Nijmegen", position: "DEF", price: 5.0 },
  { name: "D. Fonville", club: "NEC Nijmegen", position: "DEF", price: 5.0 },
  { name: "Y. Moslih", club: "NEC Nijmegen", position: "DEF", price: 5.5 },
  { name: "B. Nuytinck", club: "NEC Nijmegen", position: "DEF", price: 5.5 },
  { name: "D. Vernooij", club: "NEC Nijmegen", position: "DEF", price: 4.5 },
  { name: "P. Sandler", club: "NEC Nijmegen", position: "DEF", price: 5.5 },
  { name: "P. Schuurs", club: "NEC Nijmegen", position: "DEF", price: 8.0 },
  { name: "T. Ouwejan", club: "NEC Nijmegen", position: "DEF", price: 6.0 },
  { name: "T. Storm", club: "NEC Nijmegen", position: "DEF", price: 4.5 },
  { name: "B. Pereira", club: "NEC Nijmegen", position: "DEF", price: 5.0 },
  { name: "D. Nejašmić", club: "NEC Nijmegen", position: "MID", price: 5.5 },
  { name: "K. Sano", club: "NEC Nijmegen", position: "MID", price: 6.0 },
  { name: "S. de Laat", club: "NEC Nijmegen", position: "MID", price: 5.0 },
  { name: "W. Willumsson", club: "NEC Nijmegen", position: "MID", price: 6.0 },
  { name: "T. Chery", club: "NEC Nijmegen", position: "MID", price: 7.0 },
  { name: "I. Hansen-Aarøen", club: "NEC Nijmegen", position: "MID", price: 7.5 },
  { name: "S. Ouaissa", club: "NEC Nijmegen", position: "MID", price: 5.5 },
  { name: "N. Lebreton", club: "NEC Nijmegen", position: "MID", price: 5.0 },
  { name: "D. Proper", club: "NEC Nijmegen", position: "MID", price: 4.5 },
  { name: "J. Mustapha", club: "NEC Nijmegen", position: "FWD", price: 7.0 },
  { name: "K. Ogawa", club: "NEC Nijmegen", position: "FWD", price: 8.0 },
  { name: "B. Önal", club: "NEC Nijmegen", position: "FWD", price: 6.5 },
  { name: "B. Linssen", club: "NEC Nijmegen", position: "FWD", price: 7.5 },
  { name: "K. Kers", club: "NEC Nijmegen", position: "FWD", price: 6.0 },

  // ===================== PEC ZWOLLE =====================
  { name: "D. Verduin", club: "PEC Zwolle", position: "GK", price: 4.0 },
  { name: "L. Bakker", club: "PEC Zwolle", position: "GK", price: 3.5 },
  { name: "J. Schendelaar", club: "PEC Zwolle", position: "GK", price: 3.5 },
  { name: "N. Dobben", club: "PEC Zwolle", position: "GK", price: 2.5 },
  { name: "D. Ruward", club: "PEC Zwolle", position: "DEF", price: 4.5 },
  { name: "O. Aertssen", club: "PEC Zwolle", position: "DEF", price: 5.0 },
  { name: "S. Calderwood", club: "PEC Zwolle", position: "DEF", price: 4.5 },
  { name: "S. Graves", club: "PEC Zwolle", position: "DEF", price: 4.0 },
  { name: "S. Floranus", club: "PEC Zwolle", position: "DEF", price: 4.0 },
  { name: "J. Holtman", club: "PEC Zwolle", position: "DEF", price: 4.0 },
  { name: "D. van der Haar", club: "PEC Zwolle", position: "DEF", price: 3.5 },
  { name: "O. Velanas", club: "PEC Zwolle", position: "MID", price: 5.0 },
  { name: "J. Pereira da Gama", club: "PEC Zwolle", position: "MID", price: 5.5 },
  { name: "R. Thomas", club: "PEC Zwolle", position: "MID", price: 5.5 },
  { name: "N. Fichtinger", club: "PEC Zwolle", position: "MID", price: 5.0 },
  { name: "G. Rahajaän", club: "PEC Zwolle", position: "MID", price: 4.5 },
  { name: "G. Reiziger", club: "PEC Zwolle", position: "MID", price: 5.0 },
  { name: "L. Aelbers", club: "PEC Zwolle", position: "MID", price: 4.5 },
  { name: "G. van der Wal", club: "PEC Zwolle", position: "MID", price: 4.5 },
  { name: "C. Drost", club: "PEC Zwolle", position: "MID", price: 4.0 },
  { name: "Y. Namli", club: "PEC Zwolle", position: "FWD", price: 7.0 },
  { name: "K. Kostons", club: "PEC Zwolle", position: "FWD", price: 6.0 },
  { name: "D. Voute", club: "PEC Zwolle", position: "FWD", price: 5.5 },
  { name: "E. Sørensen", club: "PEC Zwolle", position: "FWD", price: 6.0 },
  { name: "K. de Rooij", club: "PEC Zwolle", position: "FWD", price: 5.5 },
  { name: "M. de Troije", club: "PEC Zwolle", position: "FWD", price: 5.0 },

  // ===================== PSV =====================
  { name: "T. Smolenaars", club: "PSV", position: "GK", price: 4.0 },
  { name: "N. Olij", club: "PSV", position: "GK", price: 7.0 },
  { name: "M. Kovář", club: "PSV", position: "GK", price: 8.0 },
  { name: "S. Dest", club: "PSV", position: "DEF", price: 9.0 },
  { name: "Yarek Gąsiorowski", club: "PSV", position: "DEF", price: 10.0 },
  { name: "R. Flamingo", club: "PSV", position: "DEF", price: 8.0 },
  { name: "K. Sildillia", club: "PSV", position: "DEF", price: 9.0 },
  { name: "A. Obispo", club: "PSV", position: "DEF", price: 10.0 },
  { name: "W. Kuhn", club: "PSV", position: "DEF", price: 8.0 },
  { name: "Mauro Júnior", club: "PSV", position: "DEF", price: 8.5 },
  { name: "F. Merién", club: "PSV", position: "DEF", price: 5.5 },
  { name: "N. Fernandez", club: "PSV", position: "MID", price: 9.0 },
  { name: "P. Wanner", club: "PSV", position: "MID", price: 10.0 },
  { name: "J. van den Berg", club: "PSV", position: "MID", price: 8.0 },
  { name: "J. Schouten", club: "PSV", position: "MID", price: 9.0 },
  { name: "J. Koller", club: "PSV", position: "MID", price: 7.0 },
  { name: "J. Veerman", club: "PSV", position: "MID", price: 18.0 },
  { name: "G. Til", club: "PSV", position: "MID", price: 14.0 },
  { name: "J. Bawuah", club: "PSV", position: "MID", price: 6.0 },
  { name: "I. Saibari", club: "PSV", position: "MID", price: 13.0 },
  { name: "R. van Bommel", club: "PSV", position: "FWD", price: 11.0 },
  { name: "D. Man", club: "PSV", position: "FWD", price: 12.0 },
  { name: "R. Pepi", club: "PSV", position: "FWD", price: 18.0 },
  { name: "E. Bajraktarević", club: "PSV", position: "FWD", price: 13.0 },
  { name: "I. Perišić", club: "PSV", position: "FWD", price: 9.0 },
  { name: "C. Driouech", club: "PSV", position: "FWD", price: 10.0 },
  { name: "M. Boadu", club: "PSV", position: "FWD", price: 14.0 },
  { name: "A. Pléa", club: "PSV", position: "FWD", price: 12.0 },

  // ===================== SC CAMBUUR =====================
  { name: "M. Kalisvaart", club: "SC Cambuur", position: "GK", price: 3.5 },
  { name: "J. Coehoorn", club: "SC Cambuur", position: "GK", price: 3.0 },
  { name: "J. Meijster", club: "SC Cambuur", position: "GK", price: 2.5 },
  { name: "T. Jansen", club: "SC Cambuur", position: "GK", price: 2.5 },
  { name: "F. Kvam", club: "SC Cambuur", position: "DEF", price: 4.0 },
  { name: "R. van de Pavert", club: "SC Cambuur", position: "DEF", price: 4.0 },
  { name: "J. Berkhout", club: "SC Cambuur", position: "DEF", price: 3.5 },
  { name: "J. Amofa", club: "SC Cambuur", position: "DEF", price: 4.0 },
  { name: "B. Vogelzang", club: "SC Cambuur", position: "DEF", price: 3.5 },
  { name: "J. Priem", club: "SC Cambuur", position: "DEF", price: 3.5 },
  { name: "I. Baouf", club: "SC Cambuur", position: "DEF", price: 3.5 },
  { name: "R. Mulders", club: "SC Cambuur", position: "DEF", price: 3.0 },
  { name: "A. Bakkati", club: "SC Cambuur", position: "DEF", price: 3.0 },
  { name: "W. van der Goot", club: "SC Cambuur", position: "MID", price: 4.5 },
  { name: "D. Look", club: "SC Cambuur", position: "MID", price: 4.0 },
  { name: "E. Apkakou", club: "SC Cambuur", position: "MID", price: 4.5 },
  { name: "Y. Bruinsma", club: "SC Cambuur", position: "MID", price: 4.0 },
  { name: "D. Visser", club: "SC Cambuur", position: "MID", price: 4.0 },
  { name: "W. van der Heide", club: "SC Cambuur", position: "MID", price: 4.5 },
  { name: "N. Souren", club: "SC Cambuur", position: "MID", price: 4.0 },
  { name: "N. Binder", club: "SC Cambuur", position: "FWD", price: 5.5 },
  { name: "W. Kooistra", club: "SC Cambuur", position: "FWD", price: 5.0 },
  { name: "I. Henstra", club: "SC Cambuur", position: "FWD", price: 5.0 },
  { name: "J. van der Sande", club: "SC Cambuur", position: "FWD", price: 5.0 },
  { name: "S. Vink", club: "SC Cambuur", position: "FWD", price: 4.5 },
  { name: "I. Hamache", club: "SC Cambuur", position: "FWD", price: 5.0 },

  // ===================== SC HEERENVEEN =====================
  { name: "B. Klaverboer", club: "SC Heerenveen", position: "GK", price: 4.0 },
  { name: "N. Bakker", club: "SC Heerenveen", position: "GK", price: 3.5 },
  { name: "T. Schreuder", club: "SC Heerenveen", position: "GK", price: 3.0 },
  { name: "A. Noppert", club: "SC Heerenveen", position: "GK", price: 5.0 },
  { name: "J. Bekkema", club: "SC Heerenveen", position: "GK", price: 2.5 },
  { name: "N. Hopland", club: "SC Heerenveen", position: "DEF", price: 5.5 },
  { name: "S. Kersten", club: "SC Heerenveen", position: "DEF", price: 5.0 },
  { name: "H. Petrov", club: "SC Heerenveen", position: "DEF", price: 5.0 },
  { name: "M. Egbring", club: "SC Heerenveen", position: "DEF", price: 5.0 },
  { name: "V. Zagaritis", club: "SC Heerenveen", position: "DEF", price: 4.5 },
  { name: "O. Braude", club: "SC Heerenveen", position: "DEF", price: 4.5 },
  { name: "M. Willemsen", club: "SC Heerenveen", position: "DEF", price: 4.0 },
  { name: "R. Bouw", club: "SC Heerenveen", position: "DEF", price: 4.0 },
  { name: "I. Mulder", club: "SC Heerenveen", position: "DEF", price: 4.0 },
  { name: "M. Linday", club: "SC Heerenveen", position: "MID", price: 5.5 },
  { name: "L. Smans", club: "SC Heerenveen", position: "MID", price: 5.5 },
  { name: "J. van Overeem", club: "SC Heerenveen", position: "MID", price: 6.0 },
  { name: "K. Jansen", club: "SC Heerenveen", position: "MID", price: 5.0 },
  { name: "L. Brouwers", club: "SC Heerenveen", position: "MID", price: 5.0 },
  { name: "R. Meerveld", club: "SC Heerenveen", position: "MID", price: 4.5 },
  { name: "M. Rivera", club: "SC Heerenveen", position: "MID", price: 5.5 },
  { name: "N. Courtens", club: "SC Heerenveen", position: "MID", price: 4.5 },
  { name: "I. Ahmed", club: "SC Heerenveen", position: "MID", price: 5.0 },
  { name: "K. Schaken", club: "SC Heerenveen", position: "FWD", price: 6.0 },
  { name: "J. Trenskow", club: "SC Heerenveen", position: "FWD", price: 6.5 },
  { name: "L. Oyen", club: "SC Heerenveen", position: "FWD", price: 7.0 },
  { name: "C. Bonevacia", club: "SC Heerenveen", position: "FWD", price: 6.0 },
  { name: "J. Rijssel", club: "SC Heerenveen", position: "FWD", price: 5.5 },
  { name: "E. Gürbüz", club: "SC Heerenveen", position: "FWD", price: 5.5 },
  { name: "D. Vente", club: "SC Heerenveen", position: "FWD", price: 7.5 },

  // ===================== SPARTA ROTTERDAM =====================
  { name: "R. Suur", club: "Sparta Rotterdam", position: "GK", price: 4.5 },
  { name: "P. Kuiper", club: "Sparta Rotterdam", position: "GK", price: 3.5 },
  { name: "F. Bednarek", club: "Sparta Rotterdam", position: "GK", price: 3.0 },
  { name: "B. Kuipers", club: "Sparta Rotterdam", position: "DEF", price: 5.5 },
  { name: "J. Esser", club: "Sparta Rotterdam", position: "DEF", price: 5.0 },
  { name: "T. Quintero", club: "Sparta Rotterdam", position: "DEF", price: 5.5 },
  { name: "B. Martins Indi", club: "Sparta Rotterdam", position: "DEF", price: 6.0 },
  { name: "G. Vianello", club: "Sparta Rotterdam", position: "DEF", price: 5.5 },
  { name: "M. Young", club: "Sparta Rotterdam", position: "DEF", price: 5.0 },
  { name: "N. Verschuren", club: "Sparta Rotterdam", position: "DEF", price: 4.5 },
  { name: "M. de Ligt", club: "Sparta Rotterdam", position: "DEF", price: 14.0 },
  { name: "M. Kleijn", club: "Sparta Rotterdam", position: "DEF", price: 4.5 },
  { name: "L. Martes", club: "Sparta Rotterdam", position: "MID", price: 6.0 },
  { name: "J. Baas", club: "Sparta Rotterdam", position: "MID", price: 5.5 },
  { name: "Ayoni Santos", club: "Sparta Rotterdam", position: "MID", price: 5.5 },
  { name: "J. Toornstra", club: "Sparta Rotterdam", position: "MID", price: 7.5 },
  { name: "A. Roaldsøy", club: "Sparta Rotterdam", position: "MID", price: 6.0 },
  { name: "Y. el Meftahi", club: "Sparta Rotterdam", position: "MID", price: 7.0 },
  { name: "M. van Bergen", club: "Sparta Rotterdam", position: "FWD", price: 8.0 },
  { name: "C. Terho", club: "Sparta Rotterdam", position: "FWD", price: 7.0 },
  { name: "M. Zonneveld", club: "Sparta Rotterdam", position: "FWD", price: 6.0 },
  { name: "S. Mito", club: "Sparta Rotterdam", position: "FWD", price: 6.5 },

  // ===================== TELSTAR =====================
  { name: "R. Koeman", club: "SC Telstar", position: "GK", price: 3.0 },
  { name: "D. Reiziger", club: "SC Telstar", position: "GK", price: 2.5 },
  { name: "T. Bodak", club: "SC Telstar", position: "GK", price: 2.5 },
  { name: "F. Mulder", club: "SC Telstar", position: "GK", price: 2.0 },
  { name: "G. Alders", club: "SC Telstar", position: "DEF", price: 3.5 },
  { name: "D. Bakker", club: "SC Telstar", position: "DEF", price: 3.5 },
  { name: "R. Oudsten", club: "SC Telstar", position: "DEF", price: 3.5 },
  { name: "M. Olfers", club: "SC Telstar", position: "DEF", price: 3.0 },
  { name: "Nigel Ogidi Nwankwo", club: "SC Telstar", position: "DEF", price: 3.0 },
  { name: "A. Benzzine", club: "SC Telstar", position: "DEF", price: 3.0 },
  { name: "J. Hardeveld", club: "SC Telstar", position: "DEF", price: 3.0 },
  { name: "A. Bouchouari", club: "SC Telstar", position: "DEF", price: 3.0 },
  { name: "T. Owusu", club: "SC Telstar", position: "MID", price: 4.5 },
  { name: "T. Noslin", club: "SC Telstar", position: "MID", price: 5.0 },
  { name: "N. Shenkman", club: "SC Telstar", position: "MID", price: 4.0 },
  { name: "R. Koubini", club: "SC Telstar", position: "MID", price: 4.0 },
  { name: "N. Rossen", club: "SC Telstar", position: "MID", price: 4.0 },
  { name: "P. Brouwer", club: "SC Telstar", position: "FWD", price: 5.0 },
  { name: "J. Seedorf", club: "SC Telstar", position: "FWD", price: 5.5 },
  { name: "S. Hetli", club: "SC Telstar", position: "FWD", price: 4.5 },
  { name: "K. Tejan", club: "SC Telstar", position: "FWD", price: 4.5 },

  // ===================== WILLEM II =====================
  { name: "K. de Leeuw", club: "Willem II", position: "GK", price: 4.0 },
  { name: "T. Kotte", club: "Willem II", position: "GK", price: 3.5 },
  { name: "B. van der Linden", club: "Willem II", position: "GK", price: 3.0 },
  { name: "W. van der Steen", club: "Willem II", position: "GK", price: 2.5 },
  { name: "V. van der Bas", club: "Willem II", position: "GK", price: 2.5 },
  { name: "T. Didillon-Hödl", club: "Willem II", position: "GK", price: 3.0 },
  { name: "N. Tjoe-A-On", club: "Willem II", position: "DEF", price: 5.0 },
  { name: "F. de Ruijter", club: "Willem II", position: "DEF", price: 5.0 },
  { name: "A. Ciranni", club: "Willem II", position: "DEF", price: 4.5 },
  { name: "A. Et-Taïbi", club: "Willem II", position: "DEF", price: 4.5 },
  { name: "J. Hoogma", club: "Willem II", position: "DEF", price: 5.5 },
  { name: "K. Scheepens", club: "Willem II", position: "DEF", price: 4.5 },
  { name: "J. Mathijsen", club: "Willem II", position: "DEF", price: 4.0 },
  { name: "A. Zarrouk", club: "Willem II", position: "MID", price: 5.5 },
  { name: "P. van Loon", club: "Willem II", position: "MID", price: 5.0 },
  { name: "J. van Esdonk", club: "Willem II", position: "MID", price: 5.0 },
  { name: "J. Schuurman", club: "Willem II", position: "MID", price: 5.5 },
  { name: "U. van Aalst", club: "Willem II", position: "MID", price: 5.0 },
  { name: "A. Lachkar", club: "Willem II", position: "MID", price: 5.0 },
  { name: "S. Schreuders", club: "Willem II", position: "MID", price: 5.5 },
  { name: "S. Baartmans", club: "Willem II", position: "FWD", price: 6.0 },
  { name: "D. Haen", club: "Willem II", position: "FWD", price: 6.5 },
  { name: "A. Culum", club: "Willem II", position: "FWD", price: 6.0 },
  { name: "T. Verheydt", club: "Willem II", position: "FWD", price: 7.0 },
  { name: "P. van Maarschalkerwaard", club: "Willem II", position: "FWD", price: 5.5 },
  { name: "L. Abildgaard", club: "Willem II", position: "FWD", price: 6.5 },
];

/** Auto-seed players on startup if the table is empty. */
export async function ensurePlayers() {
  const existing = db.select().from(players).all();
  if (existing.length === 0) {
    await db.insert(players).values(PLAYERS);
    console.log(`Auto-seeded ${PLAYERS.length} players.`);
  }
}

// Allow running directly: npm run db:seed
if (process.argv[1]?.includes("seed")) {
  (async () => {
    console.log("Seeding players...");
    await db.delete(players);
    await db.insert(players).values(PLAYERS);
    console.log(`Inserted ${PLAYERS.length} players.`);
  })().catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  });
}
